
#include "/vmm/bin/common.defs"
#include "/vmm/data/user_disks/vmxc/common.vmx.p3.defs"

// -- Image: vModem/vOpenWRT/LEDE
#define OPENWRT_base basedisk "/vmm/data/user_disks/test/lede-disk01.vmdk";


config "VMM_Sample_Topology" {

// ----- vModem/vCPE nodes [OpenWRT/LEDE]
//-------------------------------------------------------------------------

  vm "vm_openwrt_gw" {
    hostname "vm_openwrt_gw";
    OPENWRT_base
    ncpus 2;
    memory 128;
    setvar "boot_noveriexec" "yes";
    interface "em0" { bridge "ext"; };
    interface "em1" { bridge "NETBR_1"; };
    interface "em2" { bridge "NETBR_2"; };
    interface "em3" { bridge "NETBR_3"; };
  };

  
//## PRIVATE_BRIDGES ##//

  bridge "NETBR_1" {};
  bridge "NETBR_2" {};
  bridge "NETBR_3" {};
  bridge "NETBR_4" {};
  bridge "NETBR_5" {};
  bridge "NETBR_6" {};
  bridge "ext_gw" {};
  bridge "ext" {};
PRIVATE_BRIDGES
};


