
#include "/vmm/bin/common.defs"
#include "/vmm/data/user_disks/vmxc/common.vmx.p3.defs"

// -- Image: vSRX 3.0
#define VSRX_DISK basedisk "/vmm/data/user_disks/ihazra/junos-vsrx3-x86-64-23.2R2.21.qcow2";


config "VMM_Sample_Topology" {

// ----- vSRX nodes [VSRX 3.0]
//-------------------------------------------------------------------------

vm "vsrx" {
    hostname "vsrx-1";
    VSRX_DISK
    ncpus 1;
    memory 1024;
    interface "em0" { EXTERNAL; };
    interface "em1" { bridge "NETBR_1";  }; // ge-0/0/0
    interface "em2" { bridge "NETBR_2";  }; // ge-0/0/1
    interface "em3" { bridge "NETBR_3";  }; // ge-0/0/2
    interface "em4" { bridge "NETBR_4";  }; // ge-0/0/3

};

  
//## PRIVATE_BRIDGES ##//

  bridge "NETBR_1" {};
  bridge "NETBR_2" {};
  bridge "NETBR_3" {};
  bridge "NETBR_4" {};
  bridge "NETBR_5" {};
  bridge "NETBR_6" {};
  bridge "ext_gw" {};
  bridge "ext" {};
PRIVATE_BRIDGES
};


